CREATE TABLE public.stock_1962 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1962) TO (1963);
CREATE TABLE public.stock_1963 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1963) TO (1964);
CREATE TABLE public.stock_1964 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1964) TO (1965);
CREATE TABLE public.stock_1965 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1965) TO (1966);
CREATE TABLE public.stock_1966 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1966) TO (1967);
CREATE TABLE public.stock_1967 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1967) TO (1968);
CREATE TABLE public.stock_1968 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1968) TO (1969);
CREATE TABLE public.stock_1969 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1969) TO (1970);
CREATE TABLE public.stock_1970 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1970) TO (1971);
CREATE TABLE public.stock_1971 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1971) TO (1972);
CREATE TABLE public.stock_1972 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1972) TO (1973);
CREATE TABLE public.stock_1973 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1973) TO (1974);
CREATE TABLE public.stock_1974 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1974) TO (1975);
CREATE TABLE public.stock_1975 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1975) TO (1976);
CREATE TABLE public.stock_1976 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1976) TO (1977);
CREATE TABLE public.stock_1977 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1977) TO (1978);
CREATE TABLE public.stock_1978 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1978) TO (1979);
CREATE TABLE public.stock_1979 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1979) TO (1980);
CREATE TABLE public.stock_1980 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1980) TO (1981);
CREATE TABLE public.stock_1981 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1981) TO (1982);
CREATE TABLE public.stock_1982 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1982) TO (1983);
CREATE TABLE public.stock_1983 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1983) TO (1984);
CREATE TABLE public.stock_1984 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1984) TO (1985);
CREATE TABLE public.stock_1985 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1985) TO (1986);
CREATE TABLE public.stock_1986 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1986) TO (1987);
CREATE TABLE public.stock_1987 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1987) TO (1988);
CREATE TABLE public.stock_1988 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1988) TO (1989);
CREATE TABLE public.stock_1989 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1989) TO (1990);
CREATE TABLE public.stock_1990 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1990) TO (1991);
CREATE TABLE public.stock_1991 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1991) TO (1992);
CREATE TABLE public.stock_1992 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1992) TO (1993);
CREATE TABLE public.stock_1993 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1993) TO (1994);
CREATE TABLE public.stock_1994 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1994) TO (1995);
CREATE TABLE public.stock_1995 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1995) TO (1996);
CREATE TABLE public.stock_1996 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1996) TO (1997);
CREATE TABLE public.stock_1997 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1997) TO (1998);
CREATE TABLE public.stock_1998 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1998) TO (1999);
CREATE TABLE public.stock_1999 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (1999) TO (2000);
CREATE TABLE public.stock_2000 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2000) TO (2001);
CREATE TABLE public.stock_2001 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2001) TO (2002);
CREATE TABLE public.stock_2002 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2002) TO (2003);
CREATE TABLE public.stock_2003 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2003) TO (2004);
CREATE TABLE public.stock_2004 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2004) TO (2005);
CREATE TABLE public.stock_2005 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2005) TO (2006);
CREATE TABLE public.stock_2006 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2006) TO (2007);
CREATE TABLE public.stock_2007 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2007) TO (2008);
CREATE TABLE public.stock_2008 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2008) TO (2009);
CREATE TABLE public.stock_2009 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2009) TO (2010);
CREATE TABLE public.stock_2010 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2010) TO (2011);
CREATE TABLE public.stock_2011 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2011) TO (2012);
CREATE TABLE public.stock_2012 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2012) TO (2013);
CREATE TABLE public.stock_2013 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2013) TO (2014);
CREATE TABLE public.stock_2014 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2014) TO (2015);
CREATE TABLE public.stock_2015 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2015) TO (2016);
CREATE TABLE public.stock_2016 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2016) TO (2017);
CREATE TABLE public.stock_2017 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2017) TO (2018);
CREATE TABLE public.stock_2018 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2018) TO (2019);
CREATE TABLE public.stock_2019 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2019) TO (2020);
CREATE TABLE public.stock_2020 PARTITION OF public.stocks_statistics_partitioned 
            FOR VALUES FROM (2020) TO (2021);
